### PR TITLE
Update from deprecated channels.list api to conversations.list

### PR DESCRIPTION
**Pull request by repudi8or**
This switches the channel cache to being built via the conversations.list api instead of the deprecated channels.list api and also includes private channels the bot may be a part of in the channel cache. 

It also makes parts of the channels datastructure optional to accomodate private channels

### CODE REVIEW

**Comment by DandyDev** [comment]
Ah nice! I assume you tested this thouroughly by running a bot with this patch?

**Comment by repudi8or** [comment]
Yes I'm currently running a bot which interacts with a private channel

**Comment by repudi8or** [comment]
I would like to set up the same ci/testing you are using in my fork. Can
you please describe your setup. I'm working on a bunch of
fixes/updates/deprecated API stuff etc

**Comment by DandyDev** [comment]
I'm using Travis CI. You should be able to easily add it to your fork as well. The Travis CI configuration is in `.travis.yml`. I think if you go to the Travis CI website and add your repo, it should work.

To mimic what Travis CI is doing, locally, you can run `tox` from the root of the repo. Note: you should have both Python 3.6 and 3.7 activated for this to work. I'm personally using PyEnv to do install and manage different Python versions.

One more remark: I fixed the build on master, could you rebase your branch on master so the build succeeds here as well? Then I'll merge this PR.

**Comment by DandyDev** [comment]
@repudi8or can you do the rebase I requested?

**Comment by repudi8or** [comment]
Sorry @DandyDev was moving house all last week but back on-board now... merged master into my branch

**Pull request merged**
