### PR TITLE
add support for proxy

### PR DESCRIPTION
**Pull request by gfreezy**
add support for http proxy

### CODE REVIEW

**Comment by DandyDev** [comment]
Looks great, but the new settings should also be documented [here](https://github.com/DandyDev/slack-machine/blob/master/docs/plugins/listening.rst) If you could do that, I'll merge

**Comment by gfreezy** [comment]
The `HTTP_PROXY` and `HTTPS_PROXY` settings are not related to the bottle HTTP Server. @DandyDev Is this the right place to add the doc?

**Comment by DandyDev** [comment]
You're absolutely right! I was not looking properly. I think this is a good spot: https://github.com/DandyDev/slack-machine/blob/master/docs/user/usage.rst

**Comment by gfreezy** [comment]
@DandyDev doc added.

**Comment by gfreezy** [comment]
@DandyDev doc added.

**Comment by DandyDev** [comment]
Question: why is only HTTP proxy supported?

**Comment by DandyDev** [comment]
Looks good to me now

**Comment by gfreezy** [comment]
Is there a schedule for a new release?

**Comment by DandyDev** [comment]
Will create one tonight

**Comment by DandyDev** [comment]
Published a new version. One day later, sorry for that!

**Pull request merged**
