### PR TITLE
Migration to slack_sdk

### PR DESCRIPTION
**Pull request by Berjiz**
I think these are all the changes need for move from slack.* to slack_sdk.*

### CODE REVIEW

**Comment by Berjiz** [comment]
I seem to have accidently pushed the wrong commit to my brach. Will let you know when I fixed it

**Comment by DandyDev** [comment]
Somehow this PR also contains stuff from other PRs. I'd rather have separate PRs for different things

**Comment by Berjiz** [comment]
It's now fixed. I had accidentally merged some parts into this branch.

**Comment by DandyDev** [comment]
Due to many conflicts I had to reimplement this myself. It has been fixed in https://github.com/DandyDev/slack-machine/commit/a54ff4bf7e0382b441c5ea2d743b44167114d877

**Pull request closed without merging**
