### PR TITLE
(WIP)slack-machine: add the ability to limit commands to admins

### PR DESCRIPTION
**Pull request by preludedrew**
* List of admins will reside in local_settings.py as 'ADMIN_USERS'

### CODE REVIEW

**Comment by preludedrew** [comment]
Functional WIP. Needs a bit more work, but I wanted to get it out there as a feeler for the idea.

**Comment by davidolrik** [comment]
You might find this [plugin](https://github.com/davidolrik/slack-machine-plugin-rbac) interesting.

It's also a work in progress, but it allows protecting commands using simple decorators like so:

```python
# User must have any one of the listed roles
@respond_to(regex=r'^my cool command$')
@rbac_require_any_role(['root', 'admin'])
def my_cool_comand(self, msg):
    pass

# User must have all of the listed roles
@respond_to(regex=r'^my cool command$')
@rbac_require_all_roles(['role1', 'role2'])
def my_cool_comand(self, msg):
    pass
```

You must provide one root user in the config, and can then grant and revoke roles via two simple commands which requires the `root` or `admin` role.

**Comment by DandyDev** [comment]
That does look interesting! It might be useful to add it to the core of Slack Machine. Would you be willing to contribute your code to the core of SM @davidolrik? I don't think it even has to be a plugin. It could be part of the core decorators.

**Comment by davidolrik** [comment]
Sure - that would be even better than an external plugin.

**Comment by davidolrik** [comment]
But I like the extra commands I added - so you can grant and revoke roles dynamically.

**Pull request closed without merging**
