### PR TITLE
Updated im.open to conversations.open in machine.clients.slack.open_im(), fixed bug when bot is newly added to group chat

### PR DESCRIPTION
**Pull request by cchadowitz-pf**
When I tried using `machine.clients.slack.send_dm()` in my plugin like this:
```
def init(self):
  self.send_dm(user=user_id text="Some text here")
```

I got the following error:
```
2020-08-14 09:41:48][DEBUG] machine.core core.py:load_plugins:83 | Found a Machine plugin: plugins.custom.customPlugin
/home/user/.local/lib/python3.6/site-packages/slack/web/base_client.py:718: UserWarning: im.open is deprecated. Please use the Conversations API instead. For more info, go to https://api.slack.com/changelog/2020-01-deprecating-antecedents-to-the-conversations-api
  warnings.warn(message)
[2020-08-14 09:41:48][DEBUG] slack.web.base_client base_client.py:_urllib_api_call:420 | Sending a request - url: https://www.slack.com/api/im.open, query_params: {}, body_params: {}, files: {}, json_body: {'user': '<user_id>'}, headers: {'User-Agent': 'Python/3.6.9 slackclient/2.7.3 Linux/5.4.0-42-generic', 'Content-Type': 'application/json;charset=utf-8', 'Authorization': '(redacted)'}
[2020-08-14 09:41:53][DEBUG] slack.web.slack_response slack_response.py:validate:187 | Received the following response - status: 200, headers: {'date': 'Fri, 14 Aug 2020 13:41:53 GMT', 'server': 'Apache', 'expires': 'Mon, 26 Jul 1997 05:00:00 GMT', 'x-content-type-options': 'nosniff', 'x-slack-req-id': '<redacted>', 'cache-control': 'private, no-cache, no-store, must-revalidate', 'x-oauth-scopes': 'identify,read,post,client,apps', 'x-xss-protection': '0', 'pragma': 'no-cache', 'vary': 'Accept-Encoding', 'access-control-allow-headers': 'slack-route, x-slack-version-ts, x-b3-traceid, x-b3-spanid, x-b3-parentspanid, x-b3-sampled, x-b3-flags', 'strict-transport-security': 'max-age=31536000; includeSubDomains; preload', 'referrer-policy': 'no-referrer', 'x-slack-backend': 'r', 'access-control-expose-headers': 'x-slack-req-id, retry-after', 'access-control-allow-origin': '*', 'connection': 'close', 'transfer-encoding': 'chunked', 'content-type': 'application/json; charset=utf-8', 'x-via': '<redacted>'}, body: {'ok': False, 'error': 'method_deprecated', 'response_metadata': {'messages': ['[ERROR] This method is retired and can no longer be used. Please use conversations.open instead. Learn more: https://api.slack.com/changelog/2020-01-deprecating-antecedents-to-the-conversations-api.']}}
Traceback (most recent call last):
  File "/home/user/.local/bin/slack-machine", line 11, in <module>
    sys.exit(main())
  File "/home/user/.local/lib/python3.6/site-packages/machine/bin/run.py", line 12, in main
    bot = Machine()
  File "/home/user/.local/lib/python3.6/site-packages/machine/core.py", line 74, in __init__
    self.load_plugins()
  File "/home/user/.local/lib/python3.6/site-packages/machine/core.py", line 97, in load_plugins
    instance.init()
  File "/home/user/custom-slackbot/slackbot-docker/slackbot/plugins/custom.py", line 19, in init
    self.send_dm(user="<user_id>", text="custom Slackbot started!")
  File "/home/user/.local/lib/python3.6/site-packages/machine/plugins/base.py", line 207, in send_dm
    return self._client.send_dm(user, text, attachments=attachments, blocks=blocks, **kwargs)
  File "/home/user/.local/lib/python3.6/site-packages/machine/clients/slack.py", line 83, in send_dm
    dm_channel_id = self.open_im(user_id)
  File "/home/user/.local/lib/python3.6/site-packages/machine/clients/slack.py", line 78, in open_im
    response = LowLevelSlackClient.get_instance().web_client.im_open(user=user_id)
  File "/home/user/.local/lib/python3.6/site-packages/slack/web/client.py", line 1502, in im_open
    return self.api_call("im.open", json=kwargs)
  File "/home/user/.local/lib/python3.6/site-packages/slack/web/base_client.py", line 215, in api_call
    return self._sync_send(api_url=api_url, req_args=req_args)
  File "/home/user/.local/lib/python3.6/site-packages/slack/web/base_client.py", line 357, in _sync_send
    additional_headers=headers,
  File "/home/user/.local/lib/python3.6/site-packages/slack/web/base_client.py", line 486, in _urllib_api_call
    use_sync_aiohttp=False,
  File "/home/user/.local/lib/python3.6/site-packages/slack/web/slack_response.py", line 195, in validate
    raise e.SlackApiError(message=msg, response=self)
slack.errors.SlackApiError: The request to the Slack API failed.
The server responded with: {'ok': False, 'error': 'method_deprecated', 'response_metadata': {'messages': ['[ERROR] This method is retired and can no longer be used. Please use conversations.open instead. Learn more: https://api.slack.com/changelog/2020-01-deprecating-antecedents-to-the-conversations-api.']}}
```

Following the deprecation link, I updated `open_im()` to instead use `conversations.open`.

In addition, when the bot is added to a group chat while running, it will not trigger a `_on_channel_created()`, so I added a RTM event listener for the `group_joined` and `mpim_joined` events.

### CODE REVIEW

**Comment by cchadowitz-pf** [comment]
Not sure why the checks have failed... too many changes?

**Comment by DandyDev** [comment]
Test coverage dropped. I don't know if you added things that are easily unit tested. If so, we can add some unit tests for it.

**Comment by DandyDev** [comment]
Let me look at it this weekend and see if we can fix the failed check and then I can merge

**Comment by cchadowitz-pf** [comment]
Happy to make changes if necessary too - thanks for checking into it!

**Comment by Berjiz** [comment]
There is some kind of error in handle_message(). Everything seems to be working ok but I'm getting an error when messages are sent
[2021-04-20 20:50:12][ERROR] slack_sdk.rtm __init__.py:_dispatch_event:510 | When calling '#handle_message()' in the 'machine.dispatch' module the following error was raised: 'message'

**Comment by cchadowitz-pf** [comment]
@Berjiz is this with my proposed merge, or with the current main branch code?

@DandyDev any updates? :)

**Comment by Berjiz** [comment]
I got the error with your proposed merge, it happened several times. It seemed to be every time a slack message was sent. I tried removing the lines for handle_message in dispatch.py and the error disappeared so those lines are causing it somehow.

**Comment by Berjiz** [comment]
I just realised the error might be my fault. I forgot that python impots from the default paths so the imports are the default slack-machine instead of the repo ones. That probably caused the errors. I will fix my setup and see what happens

**Comment by cchadowitz-pf** [comment]
Nope I see it on my end as well - I'll take a closer look at it but I can see where it's happening. I think I made an assumption about the events coming in that was not 100% accurate. Great catch, thanks!!

**Comment by cchadowitz-pf** [comment]
@Berjiz I believe my latest change should fix that error. Let me know if you still see it - thanks again!

**Comment by Berjiz** [comment]
It worked, I didn't get the error with the change

**Comment by DandyDev** [comment]
Alright, I tested this branch and everything seems to work now. We're gonna ignore the failing checks due to the dropped code coverage for now.

**Comment by DandyDev** [comment]
I will cut a new release soon. There is one remaining bug (which has nothing to do with this PR) which I wanna fix first.

**Comment by DandyDev** [comment]
Ok, new release 0.21: https://pypi.org/project/slack-machine/0.21.0/

Can you check if it works for you?

**Comment by cchadowitz-pf** [comment]
A quick test seems to show that it works fine for me - I'll leave it running for a few days but I expect it'll be fine. Thanks!!

**Pull request merged**
